### ISSUE TITLE
is this project still supported

### ISSUE THREAD

**Issue by shafr** [blackducksoftware/detect_rescan#3]
@psantos1113, this project was failing due to the issue 
https://github.com/blackducksoftware/integration-gradle-inspector/issues/7

Is it still supported ? What's the replacement for jenkins junit style reports ?

**Comment by psantos1113** [comment]
Hi @shafr you'll need to direct your question to @matthewb66.

**Comment by shafr** [comment]
@matthewb66 Can you please comment one the question above ^.
 We are looking to integrating BlackDuck scan with Jenkins and it would be great to have some official solution for generation of xml reports.
Thank you.

**Comment by matthewb66** [comment]
This project is no longer maintained as most of its functionality has been superseded by features in Synopsys Detect 7 (including Rapid scan, signature scan rescan interval). It also uses Synopsys Detect 6 which does not support the latest server features.

The only feature not replaced currently is the export of Junit test outputs in XML format.

We are planning to add new integrations with advanced features such as identifying direct dependencies and upgrade guidance for transitive vulnerabilities, and exporting data in SARIF format. Currently Junit XML is not on the list of supported output formats as there was no feedback from customers that this was useful or used.

Can you please email me separately at mbrad@synopsys.com detailing your organisation and Black Duck license so we can review whether this should be added to future integrations.
